# Generated by Django 4.1.7 on 2023-03-25 12:55

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataParser', '0002_alter_regionstatistics_liter_of_water_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionstatistics',
            name='liter_of_water',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Вода (литр)'),
        ),
    ]
