# Generated by Django 4.1.7 on 2023-03-25 12:59

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataParser', '0003_alter_regionstatistics_liter_of_water'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionstatistics',
            name='trolley_bus_thoroughfare',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Проезд в троллейбусе'),
        ),
    ]
